services:
  mahasiswa_database:
    image: postgres:14
    volumes:
      - postgres_mahasiswa:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mahasiswa_db
  service_read:
    build: ./service_read
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./service_read/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@mahasiswa_database/mahasiswa_db
    depends_on:
      - mahasiswa_database
  service_update:
    build: ./service_update
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./service_update/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@mahasiswa_database/mahasiswa_db
    depends_on:
      - mahasiswa_database
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes: 
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - service_read
      - service_update

volumes:
  postgres_mahasiswa:
